# 使用单引号代替双引号
singleQuote: true
# 在语句末尾省略分号
semi: false
# 每行最多 80 个字符
printWidth: 80
# 缩进用两个空格
tabWidth: 2
# 多行时尾部逗号
trailingComma: 'es5'
# 在对象文字中打印空格
bracketSpacing: true
# 箭头函数参数只有一个时省略括号
arrowParens: 'avoid'
